name: vibcreg
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.9
  - pip
  - cudatoolkit=11.1
  - pytorch
  - numpy
  - matplotlib
  - ipython
  - scikit-learn
  - pip:
    - einops
    - wandb
    - gitpython
    - gdown
    - wfdb