package:
  name: vibcreg
  version: "0.1"

source:
  git_rev:
  git_url: https://github.com/ML4ITS/vibcreg.git

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    -

about:
  home: