# GPU
device_ids:
  - 0

# data pipeline
dataset_name: "PTB-XL"
train_fold:
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7
  - 8
val_fold: 9
test_fold: 10
train_downsampling_rate: 1.
sampling_rate: 100  # [Hz]
batch_size: 256
num_workers: 0

# augmentations
subseq_len: 250  # 2.5s * 100Hz
used_augmentations:
  - "RC"
AmpR_rate: 0.3
Vshift_rate: 0.5

# backbone-encoder
in_channels_enc: 12
n_blocks_enc:
  - 1
  - 1
  - 1
  - 1
out_channels_enc: 64
kernel_size_enc: 3
norm_layer_type_enc: "BatchNorm"
dropout_rate_enc: 0.

# framework
proj_hid_simsiam: 2048
proj_out_simsiam: 2048
norm_layer_type_proj_simsiam: "BatchNorm"
pred_hid_simsiam: 512
pred_out_simsiam: 2048
norm_layer_type_pred_simsiam: "BatchNorm"

# framework loss
#

# framework utility (belongs to the abstract class: `Utility_SSL`)
n_epochs: 100
framework_type: "simsiam"
use_wandb: True
project_name: "PTB-XL"
n_neighbors_kNN: 5
n_jobs_for_kNN: 10
model_saving_epochs:
  - 10
  - 100

# optimizer
lr: 0.001
weight_decay: 0.00001

# misc
tsne_analysis_log_epochs:
  - 1
  - 10
  - 20
  - 30
  - 40
  - 50
  - 100

