# GPU
device_ids:
  - 0

# data pipeline
dataset_name: "UCR"
ucr_dataset_name: "WordSynonyms"
train_data_ratio: 0.8
test_data_ratio: 0.2
train_random_seed: 0
test_random_seed: 0
data_scaling: True
batch_size: 256
num_workers: 0

# augmentations
subseq_len: 135
used_augmentations:
  - "RC"
  - "AmpR"
  - "Vshift"
AmpR_rate: 0.3
Vshift_rate: 0.5

# backbone-encoder
in_channels_enc: 1
ar_hid_apc: 512
n_ar_layers_apc: 1

# framework
forecast_pred_hid_apc: 512
n_pred_steps_apc:
  - 3

# framework loss
weight_on_pc_loss_apc: 1.
better_context_kind_apc: "mean+max"

# framework utility (belongs to the abstract class: `Utility_SSL`)
n_epochs: 100
framework_type: "apc"
use_wandb: True
project_name: "RLonUCR"
n_neighbors_kNN: 5
n_jobs_for_kNN: 10
model_saving_epochs:
  - 10
  - 100

# optimizer
lr: 0.001
weight_decay: 0.00001

# misc
tsne_analysis_log_epochs:
  - 1
  - 10
  - 20
  - 30
  - 40
  - 50
  - 100

# evaluation
loading_checkpoint_fname: "./checkpoints/frameworks/checkpoint-apc-ep_100.pth"
lr_clf_ev: 0.001
lr_enc_ev: 0.0001
weight_decay_ev:
  linear_evaluation: 0.00001
  fine_tuning_evaluation: 0.001
n_epochs_ev:
  linear_evaluation: 50
  fine_tuning_evaluation: 100