# data pipeline
dataset_name: "UCR"
ucr_dataset_name: "WordSynonyms"
n_data_channels: 1
train_data_ratio: 0.8
test_data_ratio: 0.2
train_random_seed: 0
test_random_seed: 0
data_scaling: True
batch_size: 256
num_workers: 0

# augmentations
subseq_len: 135
used_augmentations:
  - "RC"
  - "AmpR"
  - "Vshift"
AmpR_rate: 0.3
Vshift_rate: 0.5
