# data pipeline
dataset_name: "UCR"
ucr_dataset_name: "FiftyWords"
n_data_channels: 1
train_data_ratio: 0.8
test_data_ratio: 0.2
train_random_seed: 1
test_random_seed: 1
data_scaling: False
batch_size: 256
num_workers: 0

# misc
is_tnc_used: False
return_rc_dist: False  # True if `vibcreg_rcd` else False
use_DatasetImporterDefault: True

# augmentations
subseq_len: 135
used_augmentations:
  - "RC"
#  - "AmpR"
#  - "Vshift"
AmpR_rate: 0.3
Vshift_rate: 0.5
