# framework
proj_hid_vibcreg: 2048
proj_out_vibcreg: 2048

# framework loss
lambda_vibcreg: 25.
mu_vibcreg: 25 #25.
nu_vibcreg: 100 #10 #200.
w_simclr: 0.1
tau: 0.1
normalize: True
length_sampling: True
sample_len_ratios:
    view1:
      - 0.5
      - 0.5
#    view2:
#      - 0.2
#      - 0.5
one_sided_partial_mask: 0.3
within_augs:
  - "AmpR"
len_ratios:
  - 0.5
  - 1.0

# framework utility (belongs to the abstract class: `Utility_SSL`)
framework_type: "vibcreg_simclr"

# backbone-encoder
#backbone_type: "resnet1d"
#n_blocks_enc:
#  - 1
#  - 1
#  - 1
#  - 1
#out_channels_enc: 64
#kernel_size_enc: 3
#norm_layer_type_enc: "BatchNorm"
#dropout_rate_enc: 0.
#pool_type: 'combined2' # gap, gmp, att, combined

# TCN
#backbone_type: "tcn"
#num_channels:
#  - 32
#  - 32
#  - 32
#  - 32
#  - 64
#  - 64
#  - 64
#  - 64
#kernel_size: 3
#dropout: 0.
#pool_type: 'combined2'

# Causal CNN
#backbone_type: "causal_cnn"
#pool_type: 'combined2'

# Onion
backbone_type: "onion"
n_blocks_enc:
  - 1
  - 1
  - 1
  - 1
out_channels_enc: 256
kernel_size_enc: 3
norm_layer_type_enc: "BatchNorm"
dropout_rate_enc: 0.
pool_type: 'combined2' # gap, gmp, att, combined


# train
lr: 0.001
n_epochs: 200 #200 #100
weight_decay: 0.00001 #0.00001

# log & validation/test
project_name:
  UCR: "UCR"
  UEA: "UEA"
  PTB-XL: "PTB-XL"
n_neighbors_kNN:
  UCR: 5
  PTB-XL: 3
n_jobs_for_kNN: 10
model_saving_epochs:
  - 2
  - 10
  - 100