# framework
max_pred_step: 4

# framework loss
#

# framework utility (belongs to the abstract class: `Utility_SSL`)
framework_type: "cpc"

# backbone-encoder
backbone_type: "downsampling_cnn"
downsampling_layers_cpc:
  - 4
  - 3
  - 3
  - 2
enc_hid_channels_cpc: 512
norm_layer_type_cpc: "BatchNorm"

# train
lr: 0.001
n_epochs: 100
weight_decay: 0.00001

# log & validation/test
project_name:
  UCR: "UCR"
  PTB-XL: "PTB-XL"
n_neighbors_kNN:
  UCR: 5
  PTB-XL: 3
n_jobs_for_kNN: 10
model_saving_epochs:
  - 2
  - 10
  - 100