# framework
proj_hid_vibcreg: 4096
proj_out_vibcreg: 4096
norm_layer_type_proj_vibcreg: "BatchNorm"
add_IterN_at_the_last_in_proj_vibcreg: True

# framework loss
lambda_vibcreg: 25 #25.
mu_vibcreg: 25 #25.
nu_vibcreg: 25 #200.
rho_tnc: 25
loss_type_vibcreg: "mse"
tnc_w: 0.05

# framework utility (belongs to the abstract class: `Utility_SSL`)
framework_type: "vnibcreg"

# backbone-encoder
backbone_type: "resnet1d"
n_blocks_enc:
  - 1
  - 1
  - 1
  - 1
out_channels_enc: 64
kernel_size_enc: 3
norm_layer_type_enc: "BatchNorm"
dropout_rate_enc: 0.
pool_type: 'gap'  # gap, att

# train
lr: 0.001
n_epochs: 100 #100
weight_decay: 0.00001

# log & validation/test
project_name:
  UCR: "UCR"
  PTB-XL: "PTB-XL"
n_neighbors_kNN:
  UCR: 5
  PTB-XL: 3
n_jobs_for_kNN: 10
model_saving_epochs:
  - 2
  - 10
  - 100