# framework
proj_hid_barlow: 4096
proj_out_barlow: 4096
norm_layer_type_proj_barlow: "BatchNorm"

# framework loss
lambda_barlow: 0.005

# framework utility (belongs to the abstract class: `Utility_SSL`)
framework_type: "barlow_twins"